In [1]:
import torch

In [2]:
torch.__version__

'2.0.1+cpu'

In [3]:
e = torch.empty(2, 2)
e

tensor([[0., 0.],
        [0., 0.]])

In [4]:
r = torch.rand(2, 2)
r

tensor([[0.2835, 0.1034],
        [0.2780, 0.5527]])

In [5]:
z = torch.zeros(2, 2)
z

tensor([[0., 0.],
        [0., 0.]])

In [6]:
c = torch.full((2, 2), 3)
c

tensor([[3, 3],
        [3, 3]])

In [7]:
l = torch.tensor([[1,2], [3,4]])
l

tensor([[1, 2],
        [3, 4]])

In [8]:
import numpy
n = numpy.linspace(0, 5, 5)
n

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [9]:
nn = torch.tensor(n)
nn

tensor([0.0000, 1.2500, 2.5000, 3.7500, 5.0000], dtype=torch.float64)

In [10]:
nn.numpy()

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [11]:
nn.shape

torch.Size([5])

In [12]:
nn[1:], nn[0]

(tensor([1.2500, 2.5000, 3.7500, 5.0000], dtype=torch.float64),
 tensor(0., dtype=torch.float64))

In [13]:
s = torch.ones(3, 3, dtype = torch.float)
s

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [14]:
eye = torch.eye(3, 3)
eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [15]:
eye + torch.zeros(3, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [16]:
eye - torch.ones(3, 3)

tensor([[ 0., -1., -1.],
        [-1.,  0., -1.],
        [-1., -1.,  0.]])

In [17]:
eye * 3

tensor([[3., 0., 0.],
        [0., 3., 0.],
        [0., 0., 3.]])

In [18]:
eye / 3

tensor([[0.3333, 0.0000, 0.0000],
        [0.0000, 0.3333, 0.0000],
        [0.0000, 0.0000, 0.3333]])

In [19]:
eye * torch.full((3,3), 4)

tensor([[4., 0., 0.],
        [0., 4., 0.],
        [0., 0., 4.]])

In [20]:
x = torch.rand(3,4)
y = torch.rand(4,3)
x @ y

tensor([[1.1570, 1.6022, 1.2523],
        [0.8770, 1.5797, 1.4493],
        [1.1379, 1.3499, 1.3748]])

In [21]:
torch.tensor([1,2,5,3,4]).argmax()

tensor(2)

In [29]:
X = torch.rand(1, requires_grad = True)
X

tensor([0.2630], requires_grad=True)

In [30]:
Y = X + 1.0
Y

tensor([1.2630], grad_fn=<AddBackward0>)

In [24]:
def mse(Y):
    diff = 3.0 - Y
    return diff*diff.sum()/2

In [31]:
loss = mse(Y)
loss

tensor([1.5086], grad_fn=<DivBackward0>)

In [32]:
loss.backward()
X.grad

tensor([-1.7370])

In [33]:
learning_rate = 1e-3

In [34]:
for i in range(0, 10000):
    Y = X + 1.0
    loss = mse(Y)
    loss.backward()
    with torch.no_grad():
        X -=learning_rate*X.grad
        X.grad.zero_()
X

tensor([1.9999], requires_grad=True)

In [54]:
import pandas
from sklearn.datasets import load_iris

In [55]:
class IrisDataset:
    def __init__(self):
        iris = load_iris()
        self.data = iris.data
        self.target = iris.target

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return {
            'SepalLengthCm': self.data[idx, 0],
            'SepalWidthCm': self.data[idx, 1],
            'PetalLengthCm': self.data[idx, 2],
            'PetalWidthCm': self.data[idx, 3],
            'Species': self.target[idx]
        }

In [56]:
iris = IrisDataset()
len(iris), iris[0]

(150,
 {'SepalLengthCm': 5.1,
  'SepalWidthCm': 3.5,
  'PetalLengthCm': 1.4,
  'PetalWidthCm': 0.2,
  'Species': 0})

In [57]:
class TensorIrisDataset(IrisDataset):
    def __getitem__(self, idx):
        sample = super().__getitem__(idx)
        return {
            'tensor': torch.Tensor([
                sample['SepalLengthCm'],
                sample['SepalWidthCm'],
                sample['PetalLengthCm'],
                sample['PetalWidthCm']
            ]),
            'label': sample['Species']
        }

In [58]:
tensors = TensorIrisDataset()
len(tensors), tensors[1]

(150, {'tensor': tensor([4.9000, 3.0000, 1.4000, 0.2000]), 'label': 0})

In [59]:
from torch.utils.data import DataLoader

In [60]:
loader = DataLoader(tensors, batch_size=16, shuffle=True)

In [61]:
for batch in loader:
    print(batch)

{'tensor': tensor([[5.7000, 2.8000, 4.1000, 1.3000],
        [6.3000, 3.4000, 5.6000, 2.4000],
        [6.7000, 3.1000, 5.6000, 2.4000],
        [4.6000, 3.6000, 1.0000, 0.2000],
        [6.7000, 3.0000, 5.0000, 1.7000],
        [7.7000, 3.8000, 6.7000, 2.2000],
        [5.4000, 3.7000, 1.5000, 0.2000],
        [5.1000, 3.4000, 1.5000, 0.2000],
        [6.4000, 3.2000, 4.5000, 1.5000],
        [7.2000, 3.6000, 6.1000, 2.5000],
        [5.6000, 3.0000, 4.1000, 1.3000],
        [4.3000, 3.0000, 1.1000, 0.1000],
        [5.0000, 3.2000, 1.2000, 0.2000],
        [6.0000, 2.2000, 4.0000, 1.0000],
        [6.1000, 2.9000, 4.7000, 1.4000],
        [5.5000, 2.6000, 4.4000, 1.2000]]), 'label': tensor([1, 2, 2, 0, 1, 2, 0, 0, 1, 2, 1, 0, 0, 1, 1, 1], dtype=torch.int32)}
{'tensor': tensor([[4.9000, 3.0000, 1.4000, 0.2000],
        [6.7000, 3.1000, 4.7000, 1.5000],
        [7.1000, 3.0000, 5.9000, 2.1000],
        [6.8000, 3.0000, 5.5000, 2.1000],
        [6.8000, 3.2000, 5.9000, 2.3000],
        

# Assignment

In [62]:
torch.__version__

'2.0.1+cpu'

In [63]:
import torchvision

In [68]:
import torchvision.datasets as datasets
import torchvision.transforms as transforms

In [69]:
mnist_trainset = datasets.MNIST(root='./data', train=True, download=True, transform=transforms.ToTensor())

100%|███████████████████████████████████████████████████████████████████| 9912422/9912422 [00:03<00:00, 2480042.56it/s]


Extracting ./data\MNIST\raw\train-images-idx3-ubyte.gz to ./data\MNIST\raw



100%|███████████████████████████████████████████████████████████████████████| 28881/28881 [00:00<00:00, 1411245.79it/s]


Extracting ./data\MNIST\raw\train-labels-idx1-ubyte.gz to ./data\MNIST\raw



100%|███████████████████████████████████████████████████████████████████| 1648877/1648877 [00:01<00:00, 1503729.90it/s]


Extracting ./data\MNIST\raw\t10k-images-idx3-ubyte.gz to ./data\MNIST\raw



100%|██████████████████████████████████████████████████████████████████████████████████████| 4542/4542 [00:00<?, ?it/s]

Extracting ./data\MNIST\raw\t10k-labels-idx1-ubyte.gz to ./data\MNIST\raw



In [77]:
ten = mnist_trainset[0][0]

In [80]:
mnist_dataloader = torch.utils.data.DataLoader(mnist_trainset, batch_size=64, shuffle=True)

In [81]:
total_pixel_sum = 0.0
total_num_pixels = 0

# Iterate through batches in the dataloader
for batch in mnist_dataloader:
    images, _ = batch
    batch_pixel_sum = torch.sum(images)
    batch_num_pixels = torch.numel(images)
    
    total_pixel_sum += batch_pixel_sum
    total_num_pixels += batch_num_pixels

# Calculate the average pixel value
average_pixel_value = total_pixel_sum / total_num_pixels

print("Average Pixel Value:", average_pixel_value.item())

Average Pixel Value: 0.13066032528877258
